sudo: false
language: scala
matrix:
  include:
  - env: CMD="mill __.jvm[2.11.12].test"
    jdk: oraclejdk8

  - env: CMD="mill __.jvm[2.12.7].test"
    jdk: oraclejdk9

  - env: CMD="mill __.jvm[2.13.0-RC1].test"
    jdk: openjdk10

  - env: CMD="mill __.js[2.11.12].test"
    jdk: oraclejdk9

  - env: CMD="mill __.js[2.12.7].test"
    jdk: openjdk10

  - env: CMD="mill __.js[2.13.0-RC1].test"
    jdk: openjdk10

  - env: CMD="mill all demo.fastOpt perftests.__.compile"
    jdk: openjdk10

  - env: CMD="mill demo.fullOpt && sbt readme/run"
    jdk: oraclejdk8

script:
- curl -L -o ~/bin/mill https://github.com/lihaoyi/mill/releases/download/0.3.6/0.3.6-85-38fce6 && chmod +x ~/bin/mill
- $CMD
